//  Files Guarantees API safety ,Enables partial Updates and makes debugging easier
// src\features\survey\mappers\emptySurveyPayload.ts

export const emptySurveyPayload = {
  // ---------- Neonate ----------
  neonateQ1: "",
  neonateQ2: "",
  neonateQ3: "",
  neonateQ4: "",
  neonateQ5Ans1: "",
  neonateQ5Ans2: "",
  neonateQ5Ans3: "",
  neonateQ5Ans4: "",
  neonateQ5Ans5: "",
  neonateQ6: "",
  neonateQ7: "",
  neonateQ8: "",
  neonateQ9: "",
  neonateQ9Others: "",
  neonateQ10: "",

  // ---------- Infant ----------
  infantQ1: "",
  infantQ2Ans1: "",
  infantQ2Ans2: "",
  infantQ2Ans3: "",
  infantQ2Ans4: "",
  infantQ2Ans5: "",
  infantQ3: "",
  infantQ4: "",
  infantQ5: "",
  infantQ6: "",

  // ---------- Children ----------
  childrenQ1: "",
  childrenQ2: "",
  childrenQ3: "",
  childrenQ4: "",
  childrenQ5: "",

  // ---------- Female Adolescent Unmarried ----------
  feAdolescentUnQ1: "",
  feAdolescentUnQ2: "",
  feAdolescentUnQ3: "",
  feAdolescentUnQ4: "",
  feAdolescentUnQ5: "",
  feAdolescentUnQ6: "",
  feAdolescentUnQ7: "",
  feAdolescentUnQ8Ans1: "",
  feAdolescentUnQ8Ans2: "",
  feAdolescentUnQ8Ans3: "",
  feAdolescentUnQ8Ans4: "",
  feAdolescentUnQ8Ans5: "",
  feAdolescentUnQ9: "",
  feAdolescentUnQ10Ans1: "",
  feAdolescentUnQ10Ans2: "",
  feAdolescentUnQ10Ans3: "",
  feAdolescentUnQ10Ans4: "",
  feAdolescentUnQ10Ans5: "",

  // ---------- Female Adolescent Married ----------
  feAdolescentMaQ1: "",
  feAdolescentMaQ2: "",
  feAdolescentMaQ3: "",
  feAdolescentMaQ4: "",
  feAdolescentMaQ5: "",
  feAdolescentMaQ6: "",
  feAdolescentMaQ7: "",
  feAdolescentMaQ8: "",
  feAdolescentMaQ9: "",
  feAdolescentMaQ10: "",
  feAdolescentMaQ11: "",
  feAdolescentMaQ12Ans1: "",
  feAdolescentMaQ12Ans2: "",
  feAdolescentMaQ12Ans3: "",
  feAdolescentMaQ12Ans4: "",
  feAdolescentMaQ12Ans5: "",
  feAdolescentMaQ13: "",

  // ---------- Male Adolescent Married ----------
  maAdolescentMaQ1: "",
  maAdolescentMaQ2: "",
  maAdolescentMaQ2Others: "",
  maAdolescentMaQ3Ans1: "",
  maAdolescentMaQ3Ans2: "",
  maAdolescentMaQ3Ans3: "",
  maAdolescentMaQ3Ans4: "",
  maAdolescentMaQ3Ans5: "",
  maAdolescentMaQ4: "",
  maAdolescentMaQ5: "",

  // ---------- Reproductive ----------
  feReproductiveQ1: "",
  feReproductiveQ2: "",
  feReproductiveQ3: "",
  feReproductiveQ4: "",
  feReproductiveQ5: "",
  feReproductiveQ6: "",
  feReproductiveQ7: "",
  feReproductiveQ8: "",
  feReproductiveQ9: "",
  feReproductiveQ10Ans1: "",
  feReproductiveQ10Ans2: "",
  feReproductiveQ10Ans3: "",
  feReproductiveQ10Ans4: "",
  feReproductiveQ10Ans5: "",
  feReproductiveQ11: "",
  feReproductiveQ12Ans1: "",
  feReproductiveQ12Ans2: "",
  feReproductiveQ12Ans3: "",
  feReproductiveQ12Ans4: "",
  feReproductiveQ13: "",
  feReproductiveQ13Others: "",

  // ---------- Pregnant ----------
  pregnantWomanQ1: "",
  pregnantWomanQ2: "",
  pregnantWomanQ3: "",
  pregnantWomanQ4Ans1: "",
  pregnantWomanQ4Ans2: "",
  pregnantWomanQ4Ans3: "",
  pregnantWomanQ4Ans4: "",
  pregnantWomanQ4Ans5: "",
  pregnantWomanQ4Ans6: "",
  pregnantWomanQ4Ans7: "",
  // pregnantWomanQ4Ans8: "",
  pregnantWomanQ4Ans7Others: "",
  pregnantWomanQ5: "",
  pregnantWomanQ6: "",
  pregnantWomanQ7: "",
  pregnantWomanQ8: "",
  pregnantWomanQ9: "",
  pregnantWomanQ10: "",
  pregnantWomanQ11: "",
  pregnantWomanQ12: "",
  pregnantWomanQ13: "",

  // ---------- Postpartum ----------
  postpartumWoQ1: "",
  postpartumWoQ2: "",
  postpartumWoQ3: "",
  postpartumWoQ4: "",
  postpartumWoQ5: "",
  postpartumWoQ6: "",
  postpartumWoQ6Others: "",
  postpartumWoQ7: "",
  postpartumWoQ8: "",
  postpartumWoQ9: "",
  postpartumWoQ10: "",
  postpartumWoQ11: "",
  postpartumWoQ11Others: "",
  postpartumWoQ12: "",
  postpartumWoQ13: "",
  postpartumWoQ14: "",

  // ---------- Adult ----------
  adultMfQ1Ans1: "",
  adultMfQ1Ans2: "",
  adultMfQ1Ans3: "",
  adultMfQ1Ans4: "",
  adultMfQ1Ans5: "",
  adultMfQ1Ans6: "",
  adultMfQ1Ans7: "",
  adultMfQ1Ans8: "",
  adultMfQ1Ans9: "",
  adultMfQ1Ans10: "",
  adultMfQ1Ans11: "",
  adultMfQ1Ans11Others: "",
  adultMfQ2: "",
  adultMfQ3: "",
  adultMfQ4: "",
  adultMfQ5Ans1: "",
  adultMfQ5Ans2: "",
  adultMfQ5Ans3: "",
  adultMfQ5Ans4: "",

  // ---------- Social Protection Women ----------
  adultFQ1: "",
  adultFQ2Ans1: "",
  adultFQ2Ans2: "",
  adultFQ2Ans3: "",
  adultFQ2Ans4: "",
  adultFQ2Ans5: "",
  adultFQ2Ans6: "",
  adultFQ2Ans7: "",
  adultFQ2Ans8: "",
  adultFQ2Ans9: "",
  adultFQ2Ans10: "",
  adultFQ2Others: "",

  adultFQ3: "",

  // ---------- Disability Overlay ----------
  disableInfantQ1: "",
  disableInfantQ2Ans1: "",
  disableInfantQ2Ans2: "",
  disableInfantQ2Ans3: "",
  disableInfantQ2Ans4: "",
  disableInfantQ2Ans5: "",
  disableInfantQ2Ans6: "",
  disableInfantQ2Ans7: "",
  disableInfantQ2Ans8: "",
  disableInfantQ2Ans9: "",
  disableInfantQ2Ans10: "",
  disableInfantQ2Others: "",
  disableInfantQ3: "",
};
